AboutPage
Prains/yarregion pull request #11
Opened 2023-05-28 20:43 UTC by OlFil

1. Отступ к блоку "о Нас" на главной

2023-05-31 19:01 UTC, Prains requested changes

2023-05-31 19:01 UTC, Prains commented on src/components/Header/Header.jsx
> +        <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
выноси svg в отдельный файл .svg

2023-05-31 19:01 UTC, Prains commented on src/components/Header/Header.jsx
> +        <object
object используется для iframe или мультимедийных частей страницы

2023-05-31 19:01 UTC, Prains commented on src/components/Header/Header.jsx
> +          <img src={logo}/>
пиши альты всем Img 

https://habr.com/ru/articles/341810/

2023-05-31 19:01 UTC, Prains commented on src/components/Header/Header.jsx
> +  return <div className={styles.header}>
код безобразен по семантике 
https://habr.com/ru/companies/htmlacademy/articles/546500/

2023-05-31 19:01 UTC, Prains commented on src/components/Header/Header.jsx
> +          <li><a href="#">Новости</a></li>
вынеси огромный лист в отдельный массив и пройдись по нему методом map

2023-05-31 19:01 UTC, Prains commented on src/components/Header/Header.jsx
> +          <li><a href="#">Новости</a></li>
https://ru.react.js.org/docs/lists-and-keys.html

2023-06-01 15:07 UTC, OlFil commented on src/components/Header/Header.jsx
> +          <li><a href="#">Новости</a></li>
Сережа,привет, вроде коммит новый появился, глянь, пожалуйста

2023-06-01 15:34 UTC, Prains approved these changes

2023-06-01 15:34 UTC, merged