add info page
Prains/yarregion pull request #6
Opened 2023-05-14 08:34 UTC by Artem047

2023-05-14 08:57 UTC, Prains requested changes
ДОДЕЛАТЬ!!!

2023-05-14 08:57 UTC, Prains commented on src/components/Mainpage/Info/components/Info.jsx
> +import '../scss/css/Info.css'
https://habr.com/ru/articles/335244/

import styles from './Info.module.scss'

2023-05-14 08:57 UTC, Prains commented on src/components/Mainpage/Info/components/Info.jsx
> +import '../scss/css/Info.css'
папка components лишняя. Структура такая - components/mainpage/info
внутри Info.jsx и info.module.scss. ничего больше
если есть подкомпоненты - делаешь папку с их названием. внутрь вставляешь подкомпонент и модулированный стиль. папки scss css и result/css вырезать

2023-05-14 08:57 UTC, Prains commented on src/components/Mainpage/Info/components/Info.jsx
> +          <InfoItem
хардкод. делаешь массив объектов. {list.map((item)=>{
    return <InfoItem list={item}/>
})}

2023-05-14 08:57 UTC, Prains commented on src/components/Mainpage/Info/components/Info.jsx
> +          <InfoItem
тот же хардкод

2023-05-14 08:57 UTC, Prains commented on src/components/Mainpage/Info/components/InfoItem.jsx
> +const InfoItem = (props) => {
деструктурируй все пропсы https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

2023-05-14 08:57 UTC, Prains commented on src/components/Mainpage/Info/components/Info.jsx
> +        <h1>Предпринимателю</h1>
не используй h1 в блоке, по семантике не являющимся приоритетным

2023-05-14 08:57 UTC, Prains commented on src/components/Mainpage/Info/components/Info.jsx
> +        <h2>Инвесторам</h2>
h4-h5 каждый

2023-05-14 08:57 UTC, Prains commented on src/components/Mainpage/Info/scss/css/Info.css
> +* {
все общие стили убрать и модулировать. общие правила затрагивают не только твой компонент, но чужой. модуляция нужна, чтобы все правила, которые ты пишешь, не заставили сгореть жопу другого разраба

2023-05-14 08:57 UTC, Prains commented on src/components/Mainpage/Info/scss/Info.scss
> +*{
все общие стили убрать и модулировать. общие правила затрагивают не только твой компонент, но чужой. модуляция нужна, чтобы все правила, которые ты пишешь, не заставили сгореть жопу другого разраба

2023-05-14 08:57 UTC, Prains commented on src/components/Mainpage/Info/scss/Info.scss
> +*{
мы работаем со сборщиком проекта Vite. https://habr.com/ru/articles/251807/

Сборщик проекта сам комплирует все стили из scss в css. удали свой плагин для компиляции scss, нормальному разрабу он не нужен

2023-05-14 08:57 UTC, Prains commented on src/components/Mainpage/Info/scss/Info.scss
> +    position: absolute;
никогда не используй свойство position

2023-05-14 08:57 UTC, Prains commented on src/components/Mainpage/Info/scss/Info.scss
> +    width: 980px;
никогда не используй фиксированную ширину, если без нее не обойтись. лучше max-width и width: 100%

2023-05-14 08:57 UTC, Prains commented on src/components/Mainpage/Info/scss/Info.scss
> +    font-family: 'Montserrat', sans-serif;
шрифт везде один. повесь его на родителя

2023-05-14 08:57 UTC, Prains commented on src/components/Mainpage/Info/scss/InfoItem.scss
> +    display: flex;
все эти три стиля практически одинаковые. вынеси их в миксин

https://sass-lang.com/documentation/at-rules/mixin

2023-05-14 08:57 UTC, Prains commented on src/components/Mainpage/Info/components/Info.jsx
> +      <div className="main">
https://habr.com/ru/companies/htmlacademy/articles/546500/

обертки блоков начинаются с section

2023-05-14 08:57 UTC, Prains commented on src/components/Mainpage/Info/components/Info.jsx
> +        <div className="middle">
article

2023-05-14 08:57 UTC, Prains commented on src/components/Mainpage/Info/components/InfoItem.jsx
> +      <div>
article

2023-05-14 08:57 UTC, Prains commented on src/components/Mainpage/Info/components/Info.jsx
> +        <div className="lowest">
тоже article

2023-05-16 14:51 UTC, PazificDev commented on src/components/Mainpage/Info/InfoItem/InfoItem.jsx
> +function InfoItem(props) {
Пропсы деструктурируются через фигурные скобки и это можно сделать без создания переменной. В данном случае деструктуризация может выглядеть так: InfoItem({ text, block }) { ... }

2023-05-16 14:53 UTC, PazificDev approved these changes

2023-05-16 16:40 UTC, Prains requested changes
чуть чуть доделать

2023-05-16 16:40 UTC, Prains commented on src/components/Mainpage/Info/InfoItem/InfoItem.jsx
> +import it from './InfoItem.module.scss'
Всегда называй импорт стилей styles - так разработчики сразу могут понять, что ты импортируешь

2023-05-16 16:40 UTC, Prains commented on src/components/Mainpage/Info/Info.jsx
> +import i from "./Info.module.scss";
Всегда называй импорт стилей styles - так разработчики сразу могут понять, что ты импортируешь

2023-05-16 16:40 UTC, Prains commented on src/components/Mainpage/Info/Info.jsx
> +              {item.elements.map((elem) => {
декомпозируй map в отдельный компонент - два мапа в одном компоненте сильно портят читабельность кода и его дальнейшую поддержку.

2023-05-16 16:40 UTC, Prains commented on src/components/Mainpage/Info/Info.jsx
> +      {dataInfo.map((item) => {
каждому родителю внутри ребенка нужно давать key. это делается для того, чтобы в случае ререндеринга страницы компоненты имели свой порядок и определение внутри виртуального дерева react

2023-05-16 16:40 UTC, Prains commented on src/components/Mainpage/Info/Info.jsx
> +              {item.elements.map((elem) => {
каждому родителю внутри ребенка нужно давать key. это делается для того, чтобы в случае ререндеринга страницы компоненты имели свой порядок и определение внутри виртуального дерева react

2023-05-16 16:40 UTC, Prains commented on src/components/Mainpage/Info/Info.module.scss
> +    font-style: normal;
лишнее правило, шрифт по умолчанию стоит normal

2023-05-16 16:40 UTC, Prains commented on src/components/Mainpage/Info/InfoItem/InfoItem.module.scss
> +@mixin blocks ($width, $height) {
молодец!

2023-05-16 16:40 UTC, Prains commented on src/components/Mainpage/Result/css/Result.module.css
> +.container {
удали эту папку

2023-05-16 16:40 UTC, Prains requested changes
чуть чуть доделать

2023-05-17 10:21 UTC, Prains requested changes
вынеси компонент в отдельную папку с именем компонента

2023-05-17 10:21 UTC, Prains commented on src/components/Mainpage/Info/Info.jsx
> +const InfoSection = ({ data, styles }) => {
один компонент - один файл. стили никогда не передавай пропсами.

2023-05-17 18:15 UTC, Prains requested changes
убрать сильную связь между компонентами

2023-05-17 18:15 UTC, Prains commented on src/components/Mainpage/Info/InfoSection/InfoSection.jsx
> +import styles from '../Info.module.scss'
для каждого компонента свой файл стилей. ориентируясь на чужой файл стилей, ты создаешь сильную связь между компонентами, делая этот компонент непереиспользуемым 

https://habr.com/ru/companies/ruvds/articles/342404/

2023-05-17 18:15 UTC, Prains commented on src/components/Mainpage/Info/Info.jsx
>  import styles from "./Info.module.scss";
сильная связь

2023-05-17 18:15 UTC, Prains requested changes
убрать сильную связь между компонентами

2023-05-17 21:01 UTC, closed without merging

2023-05-17 21:02 UTC, Prains commented
пересоздай ветку. настин пр сломал твой пр